In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest,mutual_info_classif,f_classif
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [4]:
df = pd.read_csv('/content/train.csv')
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [5]:
df.shape

(2000, 21)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [8]:
X = df.iloc[:,:-1]
y = df.price_range

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
lr = LogisticRegression()

In [15]:
lr.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [16]:
lr.score(X_train,y_train)*100

63.5625

In [17]:
lr.score(X_test,y_test)*100

63.24999999999999

In [18]:
y_pred = lr.predict(X_test)

In [20]:
confusion_matrix(y_test,y_pred)

array([[79, 25,  1,  0],
       [17, 46, 20,  8],
       [ 0, 17, 46, 29],
       [ 0,  1, 29, 82]])

In [21]:
accuracy_score(y_test,y_pred)*100

63.24999999999999

In [23]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.75      0.79       105
           1       0.52      0.51      0.51        91
           2       0.48      0.50      0.49        92
           3       0.69      0.73      0.71       112

    accuracy                           0.63       400
   macro avg       0.63      0.62      0.62       400
weighted avg       0.64      0.63      0.63       400



In [24]:
mn = MinMaxScaler()

In [25]:
X_train = mn.fit_transform(X_train)
X_test = mn.transform(X_test)

In [26]:
lrr = LogisticRegression()

In [27]:
lrr.fit(X_train,y_train)

LogisticRegression()

In [28]:
lrr.score(X_train,y_train)*100

93.8125

In [29]:
lrr.score(X_test,y_test)*100

94.0

In [30]:
y_pred = lrr.predict(X_test)

In [31]:
accuracy_score(y_test,y_pred)*100

94.0

In [32]:
confusion_matrix(y_test,y_pred)

array([[105,   0,   0,   0],
       [  1,  86,   4,   0],
       [  0,   9,  77,   6],
       [  0,   0,   4, 108]])

In [33]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       105
           1       0.91      0.95      0.92        91
           2       0.91      0.84      0.87        92
           3       0.95      0.96      0.96       112

    accuracy                           0.94       400
   macro avg       0.94      0.94      0.94       400
weighted avg       0.94      0.94      0.94       400



In [34]:
k = SelectKBest(f_classif,k=10)

In [36]:
k.fit_transform(X,y)

array([[8.420e+02, 7.000e+00, 1.880e+02, ..., 9.000e+00, 7.000e+00,
        1.900e+01],
       [1.021e+03, 5.300e+01, 1.360e+02, ..., 1.700e+01, 3.000e+00,
        7.000e+00],
       [5.630e+02, 4.100e+01, 1.450e+02, ..., 1.100e+01, 2.000e+00,
        9.000e+00],
       ...,
       [1.911e+03, 3.600e+01, 1.080e+02, ..., 9.000e+00, 1.000e+00,
        5.000e+00],
       [1.512e+03, 4.600e+01, 1.450e+02, ..., 1.800e+01, 1.000e+01,
        1.900e+01],
       [5.100e+02, 4.500e+01, 1.680e+02, ..., 1.900e+01, 4.000e+00,
        2.000e+00]])

In [37]:
scores = k.scores_

In [39]:
scor = pd.Series(scores,index=X.columns)
scor.nlargest(10)

ram              3520.110824
battery_power      31.598158
px_width           22.620882
px_height          19.484842
mobile_wt           3.594318
int_memory          2.922996
n_cores             2.625415
sc_h                2.225984
sc_w                1.671000
talk_time           1.628811
dtype: float64

In [40]:
sc = df.corr()['price_range'].nlargest(11)

In [41]:
sc

price_range      1.000000
ram              0.917046
battery_power    0.200723
px_width         0.165818
px_height        0.148858
int_memory       0.044435
sc_w             0.038711
pc               0.033599
three_g          0.023611
sc_h             0.022986
fc               0.021998
Name: price_range, dtype: float64